name: CI

on:
  push:
    paths:
      - .github/workflows/**
      - "**.py"
      - "**.sh"
  pull_request:
    paths:
      - .github/workflows/**
      - "**.py"
      - "**.sh"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: [3.6, 3.7, 3.8]
        poetry: [1.0.5]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python }}
          poetry_version: ${{ matrix.poetry }}
          args: install --no-root

      - name: Run mypy
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python }}
          poetry_version: ${{ matrix.poetry }}
          args: run mypy chitchat_dataset

      - name: Run flakehell
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python }}
          poetry_version: ${{ matrix.poetry }}
          args: run flakehell lint
