name: CI

on:
  push:
    paths:
      - .github/workflows/**
      - "**.py"
      - "**.sh"
  pull_request:
    paths:
      - .github/workflows/**
      - "**.py"
      - "**.sh"

jobs:
  lint_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v1.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          pip install --upgrade pip wheel
          pip install poetry

      - name: Cache poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-root
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run mypy
        run: poetry run mypy chitchat_dataset

      - name: Run flakehell
        run: poetry run flakehell lint

      - name: Run pytest
        run: poetry run pytest --verbose
